name: laundryhub
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0' 

# ----------------- Packages -----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.4.0
  intl: ^0.20.2
  get: ^4.7.2
  url_launcher: ^6.3.1
  logger: ^2.5.0
  get_storage: ^2.1.1
  lottie: ^3.3.1
  flutter_native_splash: ^2.4.6

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8





# ----------------- ./ Packages End-----------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true

  # ----------------- Assets -----------------#
  assets:
    - assets/logos/logo_splash_dark.png
    - assets/logos/logo_splash_light.png
    - assets/Icons/brands/ 
    - assets/images/       

  # ----------------- Local Fonts -----------------#
  fonts:
    # --- coolvetica family ---
    - family: coolvetica 
      fonts: 
        - asset: assets/fonts/coolvetica_Regular.otf 
          weight: 400
        - asset: assets/fonts/coolvetica_regular_italic.otf 
          style: italic 
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf 
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
