name: laundryhub
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0' 

# ----------------- Packages -----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.4.0
  intl: ^0.20.2
  get: ^4.7.2
  url_launcher: ^6.3.1
  logger: ^2.5.0
  get_storage: ^2.1.1
  lottie: ^3.3.1
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  leak_tracker: ^10.0.9





# ----------------- ./ Packages End-----------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true

  # ----------------- Assets -----------------#
  assets:
    - assets/logos/logo_splash_dark.png
    - assets/logos/logo_splash_light.png
    - assets/Icons/brands/
    - assets/images/on_boarding_images/sammy-line-searching.gif
    - assets/images/on_boarding_images/sammy-line-no-connection.gif
    - assets/images/on_boarding_images/sammy-line-delivery.gif
    - assets/logos/google-icon.png
    - assets/logos/facebook-icon.png
    - assets/logos/email-icon.png
    - assets/images/animations/sammy-line-man-receives-a-mail.png
    - assets/images/animations/sammy-line-come-back-later.png
    - assets/images/animations/sammy-line-success.png
    - assets/images/animations/sammy-line-sale.png
    - assets/images/animations/sammy-line-workout.gif
   

  # ----------------- Local Fonts -----------------#
  fonts:
    # --- coolvetica family ---
    - family: coolvetica 
      fonts: 
        - asset: assets/fonts/coolvetica_Regular.otf 
          weight: 400
        - asset: assets/fonts/coolvetica_regular_italic.otf 
          style: italic 
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf 
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

# ----------------- Flutter Native Splash Configuration -----------------#
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logos/logo_splash_light.png
  color_dark: "#121212"
  image_dark: assets/logos/logo_splash_dark.png
  fullscreen: true
  android: true
  android_gravity: center
  ios: true
  ios_content_mode: center