name: laundryhub
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0' 

# ----------------- Packages -----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.4.0
  intl: ^0.20.2
  get: ^4.7.2
  url_launcher: ^6.3.1
  logger: ^2.5.0
  get_storage: ^2.1.1
  lottie: ^3.3.1
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  leak_tracker: 10.0.9

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1


  # Firebase Packages
  firebase_core: ^3.15.1
  connectivity_plus: ^6.1.5
  firebase_auth: 5.6.2
  firebase_storage: ^12.4.10
  image_picker: ^1.2.0
  cloud_firestore: ^5.6.12
  google_sign_in: ^7.1.1
  shimmer_animation: ^2.2.2
  shimmer: ^3.0.0





# ----------------- ./ Packages End-----------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true

  # ----------------- Assets -----------------#
  assets:
    - assets/images/user/user.png
    - assets/logos/logo_splash_dark.png
    - assets/logos/logo_splash_light.png
    - assets/icons/brands/acer_logo.png
    - assets/icons/brands/adidas-logo.png
    - assets/icons/brands/apple-logo.png
    - assets/icons/brands/herman-miller-logo.png
    - assets/icons/brands/ikea_logo.png
    - assets/icons/brands/jordan-logo.png
    - assets/icons/brands/kenwood-logo.png
    - assets/icons/brands/nike.png
    - assets/icons/brands/puma-logo.png
    - assets/icons/brands/zara-logo.png
    - assets/icons/categories/icons8-bowling-64.png
    - assets/icons/categories/icons8-cosmetics-64.png
    - assets/icons/categories/icons8-dining-chair-64.png
    - assets/icons/categories/icons8-dog-heart-64.png
    - assets/icons/categories/icons8-school-uniform-64.png
    - assets/icons/categories/icons8-shoes-64.png
    - assets/icons/categories/icons8-smartphone-64.png
    - assets/icons/categories/icons8-sparkling-diamond-64.png
    - assets/icons/categories/icons8-tailors-dummy-64.png
    - assets/icons/categories/icons8-wooden-toy-car-50.png
    - assets/images/on_boarding_images/sammy-line-searching.gif
    - assets/images/on_boarding_images/sammy-line-no-connection.gif
    - assets/images/on_boarding_images/sammy-line-delivery.gif
    - assets/logos/google-icon.png
    - assets/logos/facebook-icon.png
    - assets/logos/email-icon.png
    - assets/images/animations/sammy-line-man-receives-a-mail.png
    - assets/images/animations/sammy-line-come-back-later.png
    - assets/images/animations/sammy-line-success.png
    - assets/images/animations/sammy-line-sale.png
    - assets/images/animations/sammy-line-workout.gif
    - assets/images/promo_banners/promo-banner-3.png
    - assets/images/promo_banners/promo-banner-1.png
    - assets/images/promo_banners/promo-banner-2.png
    - assets/images/products/nike-shoes.png
    - assets/images/products/product-1.png
    - assets/images/products/product-jacket.png
    - assets/images/products/product-jeans.png
    - assets/images/products/product-shirt.png
    - assets/images/products/product-slippers.png
    - assets/images/products/NikeAirJOrdonBlackRed.png
    - assets/images/products/NikeAirJOrdonOrange.png
    - assets/images/products/NikeAirJordonwhiteMagenta.png
    - assets/images/products/NikeAirJOrdonWhiteRed.png
    - assets/images/products/samsung_s9_mobile.png
    - assets/images/products/samsung_s9_mobile_withback.png
    - assets/images/products/samsung_s9_mobile_back.png
    - assets/images/products/iphone8_mobile.png
    - assets/images/products/iphone8_mobile_back.png
    - assets/images/products/iphone8_mobile_dual_side.png
    - assets/images/products/iphone8_mobile_front.png
    - assets/images/products/tomi_dogfood.png
    - assets/images/products/NikeAirJordonSingleBlue.png
    - assets/images/products/NikeAirJordonSingleOrange.png
    - assets/images/products/NikeAirMax.png
    - assets/images/products/NikeBasketballShoeGreenBlack.png
    - assets/images/products/NikeWildhorse.png
    - assets/images/products/tracksuit_black.png
    - assets/images/products/tracksuit_blue.png
    - assets/images/products/tracksuit_red.png
    - assets/images/products/trcksuit_parrotgreen.png
    - assets/images/products/Adidas_Football.png
    - assets/images/products/baseball_bat.png
    - assets/images/products/cricket_bat.png
    - assets/images/products/tennis_racket.png
    - assets/images/products/bedroom_bed.png
    - assets/images/products/bedroom_lamp.png
    - assets/images/products/bedroom_sofa.png
    - assets/images/products/bedroom_wardrobe.png
    - assets/images/products/kitchen_counter.png
    - assets/images/products/kitchen_dining table.png
    - assets/images/products/kitchen_refrigerator.png
    - assets/images/products/office_chair_1.png
    - assets/images/products/office_chair_2.png
    - assets/images/products/office_desk_1.png
    - assets/images/products/office_desk_2.png
    - assets/images/products/bedroom_bed_black.png
    - assets/images/products/bedroom_bed_grey.png
    - assets/images/products/bedroom_bed_simple_brown.png
    - assets/images/products/bedroom_bed_with_comforter.png
    - assets/images/products/acer_laptop_1.png
    - assets/images/products/acer_laptop_2.png
    - assets/images/products/acer_laptop_3.png
    - assets/images/products/acer_laptop_4.png
    - assets/images/products/iphone_13_pro.png
    - assets/images/products/iphone_14_pro.png
    - assets/images/products/iphone_14_white.png
    - assets/images/products/product-shirt_blue_1.png
    - assets/images/products/product-shirt_blue_2.png
    - assets/images/products/acer_laptop_var_1.png
    - assets/images/products/acer_laptop_var_2.png
    - assets/images/products/acer_laptop_var_3.png
    - assets/images/products/acer_laptop_var_4.png
    - assets/images/products/tshirt_red_collar.png
    - assets/images/products/tshirt_yellow_collar.png
    - assets/images/products/tshirt_green_collar.png
    - assets/images/products/tshirt_blue_collar.png
    - assets/images/products/leather_jacket_1.png
    - assets/images/products/leather_jacket_2.png
    - assets/images/products/leather_jacket_3.png
    - assets/images/products/leather_jacket_4.png
    - assets/images/products/tshirt_blue_without_collar_back.png
    - assets/images/products/tshirt_blue_without_collar_front.png
    - assets/images/products/iphone_12_red.png
    - assets/images/products/iphone_12_blue.png
    - assets/images/products/iphone_12_green.png
    - assets/images/products/iphone_12_black.png
    - assets/images/products/slipper-product-1.png
    - assets/images/products/slipper-product-2.png
    - assets/images/products/slipper-product-3.png
    - assets/images/products/slipper-product.png
    - assets/images/reviews/review_profile_image_1.jpg
    - assets/images/reviews/review_profile_image_1.jpg
    - assets/images/reviews/review_profile_image_3.jpeg
    - assets/icons/payment_methods/apple-pay.png
    - assets/icons/payment_methods/credit-card.png
    - assets/icons/payment_methods/google-pay.png
    - assets/icons/payment_methods/master-card.png
    - assets/icons/payment_methods/paypal.png
    - assets/icons/payment_methods/paystack.png
    - assets/icons/payment_methods/paytm.png
    - assets/icons/payment_methods/successful_payment_icon.png
    - assets/icons/payment_methods/visa.png
   

  # ----------------- Local Fonts -----------------#
  fonts:
    # --- coolvetica family ---
    - family: coolvetica 
      fonts: 
        - asset: assets/fonts/coolvetica_Regular.otf 
          weight: 400
        - asset: assets/fonts/coolvetica_regular_italic.otf 
          style: italic 
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf 
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

# ----------------- Flutter Native Splash Configuration -----------------#
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logos/logo_splash_light.png
  color_dark: "#121212"
  image_dark: assets/logos/logo_splash_dark.png
  fullscreen: true
  android: true
  android_gravity: center
  ios: true
  ios_content_mode: center