// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6B4C_ETPcaO5_r0YvIDz92zE4VA82gIA',
    appId: '1:822733233373:web:e22519915ac0605f22cf34',
    messagingSenderId: '822733233373',
    projectId: 'ecommerceapp-6e6c9',
    authDomain: 'ecommerceapp-6e6c9.firebaseapp.com',
    storageBucket: 'ecommerceapp-6e6c9.firebasestorage.app',
    measurementId: 'G-L68Y8RBRCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjTkTRTubHuPzEie0wucGTNDvehDvD9UA',
    appId: '1:822733233373:android:e732c21f3efad7fa22cf34',
    messagingSenderId: '822733233373',
    projectId: 'ecommerceapp-6e6c9',
    storageBucket: 'ecommerceapp-6e6c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjYDNhdUVPO86iUDSxj-8KdrNQRG68ql4',
    appId: '1:822733233373:ios:098c3a8087c5a3a022cf34',
    messagingSenderId: '822733233373',
    projectId: 'ecommerceapp-6e6c9',
    storageBucket: 'ecommerceapp-6e6c9.firebasestorage.app',
    androidClientId: '822733233373-vd0gns7aaeaj2f8lgjivo3bg0ulpj6lp.apps.googleusercontent.com',
    iosClientId: '822733233373-od99s9d8vuob3k58p7fa92f4ti4ah7sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundryhub',
  );

}